import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Spotlight } from "@/components/ui/spotlight-new";
import { NavbarDemo } from "@/components/layout/resizable-navbar-demo";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Festus Portfolio | Software Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-neutral-950">
        {/* Background */}
        <div className="fixed inset-0 z-0 overflow-hidden ">
          <Spotlight />
        </div>
        <div>
        <NavbarDemo />
        </div>
        {children}
      </body>
    </html>
  );
}
